name: Run

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/run.yml'
      - 'Datasets/*.txt'
      - 'TopKMining.java'
      - 'draw.py'
      - 'requirements.txt'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/run.yml'
      - 'Datasets/*.txt'
      - 'TopKMining.java'
      - 'draw.py'
      - 'requirements.txt'
  workflow_dispatch:
    inputs:
      testAccidents:
        description: 'accidents.txt'
        required: true
        default: true
        type: boolean
      testChess:
        description: 'chess.txt'
        required: true
        default: true
        type: boolean
      testConnect:
        description: 'connect.txt'
        required: true
        default: true
        type: boolean
      testKosarak:
        description: 'kosarak.txt'
        required: true
        default: true
        type: boolean
      testMushroom:
        description: 'mushroom.txt'
        required: true
        default: true
        type: boolean
      testPumsb:
        description: 'pumsb.txt'
        required: true
        default: true
        type: boolean
      testPumsbStar:
        description: 'pumsb_star.txt'
        required: true
        default: true
        type: boolean
      testRetail:
        description: 'retail.txt'
        required: true
        default: true
        type: boolean
      testSample:
        description: 'sample.txt'
        required: true
        default: true
        type: boolean
      javaVersion:
        description: 'Java version'
        required: true
        default: 25
        type: choice
        options:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
      outputFormat:
        description: 'Output format'
        required: true
        default: '.csv'
        type: choice
        options:
          - '.csv'
          - '.htm'
          - '.html'
          - '.json'
          - '.tex'
          - '.tsv'
          - '.xml'
      runCount:
        description: 'Run count'
        required: true
        default: '1'
        type: string
      pythonVersion:
        description: 'Python version'
        required: true
        default: '3.x'
        type: choice
        options:
          - '3.x'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Prepare the matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]];
          then
            testAccidents="${{ github.event.inputs.testAccidents }}"
            testChess="${{ github.event.inputs.testChess }}"
            testConnect="${{ github.event.inputs.testConnect }}"
            testKosarak="${{ github.event.inputs.testKosarak }}"
            testMushroom="${{ github.event.inputs.testMushroom }}"
            testPumsb="${{ github.event.inputs.testPumsb }}"
            testPumsbStar="${{ github.event.inputs.testPumsbStar }}"
            testRetail="${{ github.event.inputs.testRetail }}"
            testSample="${{ github.event.inputs.testSample }}"
          else
            testAccidents="false"
            testChess="true"
            testConnect="false"
            testKosarak="false"
            testMushroom="true"
            testPumsb="false"
            testPumsbStar="false"
            testRetail="false"
            testSample="true"
          fi
          matrix=()
          [[ "true" == "${testAccidents}" ]] && matrix+=("Datasets/accidents.txt")
          [[ "true" == "${testChess}" ]] && matrix+=("Datasets/chess.txt")
          [[ "true" == "${testConnect}" ]] && matrix+=("Datasets/connect.txt")
          [[ "true" == "${testKosarak}" ]] && matrix+=("Datasets/kosarak.txt")
          [[ "true" == "${testMushroom}" ]] && matrix+=("Datasets/mushroom.txt")
          [[ "true" == "${testPumsb}" ]] && matrix+=("Datasets/pumsb.txt")
          [[ "true" == "${testPumsbStar}" ]] && matrix+=("Datasets/pumsb_star.txt")
          [[ "true" == "${testRetail}" ]] && matrix+=("Datasets/retail.txt")
          [[ "true" == "${testSample}" ]] && matrix+=("Datasets/sample.txt")
          if [[ ${#matrix[@]} -ge 1 ]];
          then
            echo "matrix=$(printf '%s\n' "${matrix[@]}" | jq -R . | jq -s -c 'unique')" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix=[]" >> "${GITHUB_OUTPUT}"
          fi
  
  runJava:
    if: needs.prepare.outputs.matrix != '[]'
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dataset: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            Datasets
            TopKMining.java
      
      - name: Get ready
        id: ready
        run: |
          cd "${{ github.workspace }}"
          
          # Run count #
          integerNumberString="$(echo -n "${runCountString}" | tr -cd '0-9A-Za-z+.-' | tr 'A-Z' 'a-z')"
          leadingSigns="${integerNumberString%%[!+-]*}"
          minusCount=$(echo -n "${leadingSigns}" | tr -cd '-' | wc -c)
          integerNumberString="${integerNumberString#$leadingSigns}"
          if [[ "${integerNumberString:0:1}" =~ [0-9] ]];
          then
            case "${integerNumberString: -1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              *)
                radix=10
                ;;
            esac
          else
            case "${integerNumberString:0:1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:1}"
                ;;
              *)
                radix=10
                ;;
            esac
          fi
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          integerNumberString="${integerNumberString%%.*}"
          runCount=1
          { runCount=$((${radix}#$integerNumberString)); } 2>/dev/null
          if (( minusCount % 2 == 1 ));
          then
            runCount=$(( -runCount ))
          fi
          if [[ ${runCount} -lt 1 ]];
          then
            runCount=1
          fi
          
          directoryPath="Outputs"
          mainFileName="$(basename "${{ matrix.dataset }}" | sed "s/\.[^.]*\$//g")"
          timeString="HKT$(date '+%Y%m%d%H%M%S')"
          outputFilePath="${directoryPath}/${mainFileName}-Java${javaVersion}-r${runCount}-${timeString}${outputFormat}"
          outputFileName="$(basename "${outputFilePath}")"
          echo "Dataset: ${{ matrix.dataset }}"
          echo "Java version: ${javaVersion}"
          echo "Run count: ${runCountString} (${runCount})"
          echo "Time string: ${timeString}"
          echo "Output file path: ${outputFilePath}"
          echo "javaVersion=${javaVersion}" >> "${GITHUB_OUTPUT}"
          echo "runCount=${runCount}" >> "${GITHUB_OUTPUT}"
          echo "timeString=${timeString}" >> "${GITHUB_OUTPUT}"
          echo "outputFilePath=${outputFilePath}" >> "${GITHUB_OUTPUT}"
        env:
          javaVersion: ${{ github.event.inputs.javaVersion || 25 }}
          runCountString: ${{ github.event.inputs.runCount || '1' }}
          TZ: 'Asia/Hong_Kong'
          outputFormat: ${{ github.event.inputs.outputFormat || '.csv' }}
      
      - name: Set up JDK ${{ steps.ready.outputs.javaVersion }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.ready.outputs.javaVersion }}
          distribution: 'temurin'
      
      - name: Test on the dataset
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f "${{ matrix.dataset }}" ]];
          then
            echo "\$ java TopKMining.java -d \"${{ matrix.dataset }}\" -l Trace -o \"${{ steps.ready.outputs.outputFilePath }}\" -r ${{ steps.ready.outputs.runCount }}"
            java TopKMining.java -d "${{ matrix.dataset }}" -l Trace -o "${{ steps.ready.outputs.outputFilePath }}" -r ${{ steps.ready.outputs.runCount }}
          else
            echo "Could not test on the dataset \"${{ matrix.dataset }}\" via Java. "
            tree
            exit 1
          fi
      
      - name: Upload the result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
          archive: false
          if-no-files-found: error
  
  runPython:
    if: ${{ github.event.inputs.outputFormat || '.csv' }} == '.csv'
    needs: runJava
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            draw.py
            requirements.txt
      
      - name: Get ready
        id: ready
        run: |
          cd "${{ github.workspace }}"
          directoryPath="Outputs"
          mainFileName="summaries"
          timeString="HKT$(date '+%Y%m%d%H%M%S')"
          resultLaTeXFilePath="${directoryPath}/${mainFileName}-Python${pythonVersion}-${timeString}.tex"
          resultPDFFilePath="${directoryPath}/${mainFileName}-Python${pythonVersion}-${timeString}.pdf"
          echo "Directory path: ${directoryPath}"
          echo "Time string: ${timeString}"
          echo "Result LaTeX file path: ${resultLaTeXFilePath}"
          echo "Result PDF file path: ${resultPDFFilePath}"
          echo "Python version: ${pythonVersion}"
          echo "directoryPath=${directoryPath}" >> "${GITHUB_OUTPUT}"
          echo "timeString=${timeString}" >> "${GITHUB_OUTPUT}"
          echo "resultLaTeXFilePath=${resultLaTeXFilePath}" >> "${GITHUB_OUTPUT}"
          echo "resultPDFFilePath=${resultPDFFilePath}" >> "${GITHUB_OUTPUT}"
          echo "pythonVersion=${pythonVersion}" >> "${GITHUB_OUTPUT}"
        env:
          pythonVersion: ${{ github.event.inputs.pythonVersion || '3.x' }}
          TZ: 'Asia/Hong_Kong'
      
      - name: Gather artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: ${{ github.workspace }}/${{ steps.ready.outputs.directoryPath }}
      
      - name: Install system dependencies
        run: |
          cd "${{ github.workspace }}"
          sudo apt-get update
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install -y texlive-latex-extra ttf-mscorefonts-installer
      
      - name: Set up Python ${{ steps.ready.outputs.pythonVersion }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ steps.ready.outputs.pythonVersion }}
      
      - name: Install Python dependencies
        run: |
          cd "${{ github.workspace }}"
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install -r requirements.txt
      
      - name: Build LaTeX and the PDF for the result
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f draw.py && -d "${{ steps.ready.outputs.directoryPath }}" ]];
          then
            echo "\$ python draw.py \"${{ steps.ready.outputs.directoryPath }}\""
            python draw.py "${{ steps.ready.outputs.directoryPath }}"
            mv "${{ steps.ready.outputs.directoryPath }}/summaries.tex" "${{ steps.ready.outputs.resultLaTeXFilePath }}"
            mv "${{ steps.ready.outputs.directoryPath }}/summaries.pdf" "${{ steps.ready.outputs.resultPDFFilePath }}"
          else
            echo "Could not execute \"draw.py\" via Python ${{ steps.ready.outputs.pythonVersion }}. "
            tree
          fi
      
      - name: Upload the figures for the result
        uses: actions/upload-artifact@v7
        with:
          name: figures-Python${{ steps.ready.outputs.pythonVersion }}-${{ steps.ready.outputs.timeString }}.zip
          path: ${{ github.workspace }}/${{ steps.ready.outputs.directoryPath }}/*.pdf
          if-no-files-found: warn
      
      - name: Upload the LaTeX source code for the result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.resultLaTeXFilePath }}
          archive: false
          if-no-files-found: warn
      
      - name: Upload the PDF for the result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.resultPDFFilePath }}
          archive: false
          if-no-files-found: warn